device: "cuda:1"

task2vec:
  # Maximum number of samples in the dataset used to estimate the Fisher
  max_samples: 10000
  skip_layers: 0

  # Whether to put batch normalization in eval mode (true) or train mode (false) when computing the Fisher
#  fix_batch_norm: true

classifier_opts:
    optimizer: adam
    epochs: 10
    learning_rate: 0.0004
    weight_decay: 0.0001

defaults:
  - task2vec: montecarlo

dataset:
  name: PCam
#  task_id: 1
#  root: ~/data
#  root: ~/downloads/Internship
  root: /data/ivdbrandt

# Probe network to use
model:
  arch: resnet50
  pretrained: true

loader:
  batch_size: 100
  num_workers: 6
  balanced_sampling: true
  num_samples: 10000

hydra:
  sweep:
    dir: ./multirun/${task2vec_fullcode.method}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
#    subdir: ${hydra.job.num}_${hydra.job.num}_${hydra.job.override_dirname}

